/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput/SearchInput.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TableBody: typeof import('./src/components/Table/components/TableBody.vue')['default']
    TableHeader: typeof import('./src/components/Table/components/TableHeader.vue')['default']
    TableLoader: typeof import('./src/components/Table/components/TableLoader.vue')['default']
  }
}
